### ISSUE TITLE
local file

### ISSUE THREAD

**Issue by Z1VC0H3N** [harismh/react-native-webview-track-player#1]
how to use local file uri? (currently on ios) , when using local file uri the audio isn't loading

**Comment by harismh** [comment]
Hey there, apologies for getting back so late. Thanks for trying it out. 

Because I use iframes/WebViews to streamline cross-platform compatibility, I also inherit all of their limitations. That includes file system access which isn't supported yet, unfortunately. The latest browser support can be found here: https://developer.mozilla.org/en-US/docs/Web/API/File_System_API#browser_compatibility. 

Looking at that now, it seems iOS may be possible but Android is out of luck. Since this library aims to have the same functionality across all platforms, I have to close this issue for now.
